name: Sync
on:
  workflow_dispatch:
  push:
    branches: ["main"]

jobs:
  github-team:
    runs-on: ubunutu-linux
    steps:
      - uses: actions/checkout@v5
      - uses: cachix/install-nix-action@v31
        with:
          nix_path: nixpkgs=channel:nixos-unstable
